### ISSUE TITLE
Update README with Current Status

### ISSUE THREAD

**Issue by davelab6** [xmlsh/xmlsh#1]
README says, 

> This GitHub repository is for the development of xmlsh 2.0. It is currently IN-DEVELOPMENT. I am not tracking branches or releases yet until its stable enough to publish, ETA by end of Oct 2014.

What is the current status? :)

**Comment by DALDEI** [comment]
Current status is 'IN-DEVELOPMENT'

I will update the ETA to be 'Unknown'
It is reasonably stable but there are several planned changes that may make it less backwards compatible.
Namely 
1) Inclusion of inline code from other languages (JavaScript, Groovy, Kotlin etc)

2) Modifying the behaviour of quoting - or introducing 2 modes -- More and more I find it unbearably awkward to have to use    "${var}"  everywhere I simply want $var , let alone "${var[@]}" -- 
The original shell was not designed to handle filenames with spaces, sequences, or non-string variables making modern use of even bash a bit of a torture.

3) Named parameters to functions

4) Annotations 

5) Function variables and literals 

Many of these will require some non-compatible changes to the syntax.

**Comment by davelab6** [comment]
Cool :) thanks for the update!
